version: "3"

tasks:
  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf bin .pgo_gen
  test:
    desc: Run tests
    cmds:
      - mkdir -p internal/transpile/lang
      - cp lang/*.json internal/transpile/lang/
      - go test ./...
  build:
    desc: Build polygo binary
    cmds:
      - mkdir -p internal/transpile/lang
      - cp lang/*.json internal/transpile/lang/
      - go build -o bin/pgo ./cmd/pgo
